#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a55x-common

PRODUCT_COPY_FILES += \
    vendor/samsung/a55x-common/proprietary/product/etc/permissions/privapp-permissions-google-product.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-google-product.xml \
    vendor/samsung/a55x-common/proprietary/product/etc/sysconfig/asi_features.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/asi_features.xml \
    vendor/samsung/a55x-common/proprietary/product/etc/sysconfig/sysconfig_contextual_search.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/sysconfig_contextual_search.xml \
    vendor/samsung/a55x-common/proprietary/product/etc/sysconfig/sysconfig_gemini.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/sysconfig_gemini.xml \
    vendor/samsung/a55x-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/Khronos/OpenCL/samsung.icd:$(TARGET_COPY_OUT_VENDOR)/etc/Khronos/OpenCL/samsung.icd \
    vendor/samsung/a55x-common/proprietary/vendor/etc/dqe/calib_data_colormode0_off.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_off.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/ems.json:$(TARGET_COPY_OUT_VENDOR)/etc/ems.json \
    vendor/samsung/a55x-common/proprietary/vendor/etc/ems_parameter.json:$(TARGET_COPY_OUT_VENDOR)/etc/ems_parameter.json \
    vendor/samsung/a55x-common/proprietary/vendor/etc/epic.json:$(TARGET_COPY_OUT_VENDOR)/etc/epic.json \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.dcm.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.dcm.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.dcm.debug.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.dcm.debug.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.dcm.issuetracker.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.dcm.issuetracker.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.debug.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.debug.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.issuetracker.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.issuetracker.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.kdi.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.kdi.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.kdi.debug.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.kdi.debug.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.kdi.issuetracker.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.kdi.issuetracker.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init.insmod.vendor_dlkm.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.vendor_dlkm.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/android.hardware.graphics.allocator-aidl-service-sgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator-aidl-service-sgr.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.samsung.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/dmd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dmd.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/hermesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hermesd.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/hwc3.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hwc3.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.baseband.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.baseband.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.exynos.wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.exynos.wifi.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.fingerprint.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fingerprint.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.gps.rose.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rose.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.nfc.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.nfc.samsung.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.sensorhub.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sensorhub.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.vendor.onebinary.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.onebinary.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/samsung.hardware.media.c2@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/samsung.hardware.media.c2@1.2-service.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/sec-nfc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/sec-nfc-service.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/secaudiohalaidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secaudiohalaidl.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/teegris.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss-service.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.hardware.security.hermes.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.security.hermes.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.hardware.vibrator-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.vibrator-default.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.rilchip.slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rilchip.slsi.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/wifi_slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_slsi.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/libnfc-sec-vendor.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-sec-vendor.conf \
    vendor/samsung/a55x-common/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/media_codecs_performance_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_c2.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/mixer_gains.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_gains.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/nfc/sec_s3nsen6_hwreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nsen6_hwreg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/nfc/sec_s3nsen6_swreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nsen6_swreg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta_ltn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_ltn.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_se13_prebuilt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13_prebuilt.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/sec_audio_volume_curve.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sec_audio_volume_curve.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base.policy \
    vendor/samsung/a55x-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext.policy \
    vendor/samsung/a55x-common/proprietary/vendor/etc/secnvm/k250a_41000001_1.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_41000001_1.img \
    vendor/samsung/a55x-common/proprietary/vendor/etc/secnvm/k250a_41000003_0.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_41000003_0.img \
    vendor/samsung/a55x-common/proprietary/vendor/etc/secnvm/k250a_41000005_c.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_41000005_c.img \
    vendor/samsung/a55x-common/proprietary/vendor/etc/sound_trigger_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_info.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info \
    vendor/samsung/a55x-common/proprietary/vendor/etc/wifi/init.insmod.wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/init.insmod.wifi.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/OD_V3.4.10_11_17_QVGA_ROSE_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.4.10_11_17_QVGA_ROSE_ENN_BGRA.nnc \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/OD_V3.5.3_06_12_VGA_ROSE_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.5.3_06_12_VGA_ROSE_ENN_BGRA.nnc \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/SoundAlive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundAlive.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_solution.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_solution_rev00.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution_rev00.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_solution_ti.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution_ti.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_system.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_system.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/compress_capture.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/compress_capture.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/dolby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dolby.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xdcm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xdcm.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xkdi.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xkdi.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xnaxx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xnaxx.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xnsxx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xnsxx.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xskt.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xskt.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xzc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xzc.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xzh.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xzh.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/icc_profile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/icc_profile.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/is_mcu_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/is_mcu_fw.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/lc3dec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lc3dec.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/lc3enc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lc3enc.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/param_ti.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/param_ti.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/sb_ll.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_ll.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/sb_music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_music.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/sb_others.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_others.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/spkamp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/spkamp.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/volctrl.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volctrl.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/bt/log-strings.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/bt/log-strings.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/common/log-strings.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/common/log-strings.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/btwl/btwl/moredump/btwl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/btwl/btwl/moredump/btwl_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM0Plus.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM0Plus.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_dbg.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_dbg.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_dwt.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_dwt.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_etm.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_etm.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_fpb.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_fpb.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_itm.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_itm.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_mpu.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_mpu.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_nvic.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_nvic.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_scs.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_scs.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_tpi.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_tpi.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_dbg.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_dbg.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_dwt.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_dwt.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_fpb.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_fpb.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_itm.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_itm.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_mpu.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_mpu.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_nvic.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_nvic.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_scs.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_scs.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexR7.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexR7.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/moredump.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/moredump.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/moredump.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/moredump.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_ap2bt/moredump/mb_ap2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_ap2bt/moredump/mb_ap2bt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_ap2pmu/moredump/mb_ap2pmu_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_ap2pmu/moredump/mb_ap2pmu_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_ap2wl/moredump/mb_ap2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_ap2wl/moredump/mb_ap2wl_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_cp2bt/moredump/mb_cp2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_cp2bt/moredump/mb_cp2bt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_cp2wl/moredump/mb_cp2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_cp2wl/moredump/mb_cp2wl_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/pert/moredump/pert_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/pert/moredump/pert_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu_conf/pmu_conf/moredump/pmu_conf_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu_conf/pmu_conf/moredump/pmu_conf_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2bt/moredump/mb_ap2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2bt/moredump/mb_ap2bt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2pmu/moredump/mb_ap2pmu_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2pmu/moredump/mb_ap2pmu_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2wl/moredump/mb_ap2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2wl/moredump/mb_ap2wl_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_cp2bt/moredump/mb_cp2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_cp2bt/moredump/mb_cp2bt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_cp2wl/moredump/mb_cp2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_cp2wl/moredump/mb_cp2wl_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/peri/moredump/peri_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/peri/moredump/peri_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_gic/moredump/periph_gic_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_gic/moredump/periph_gic_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_int_ifc/moredump/periph_int_ifc_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_int_ifc/moredump/periph_int_ifc_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_scu/moredump/periph_scu_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_scu/moredump/periph_scu_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/pert/moredump/pert_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/pert/moredump/pert_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/perw_diet/moredump/perw_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/perw_diet/moredump/perw_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/perw_pri/moredump/perw_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/perw_pri/moredump/perw_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_dwt/moredump/m3_periph_dwt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_dwt/moredump/m3_periph_dwt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_fpb/moredump/m3_periph_fpb_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_fpb/moredump/m3_periph_fpb_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_itm/moredump/m3_periph_itm_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_itm/moredump/m3_periph_itm_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_nvic/moredump/m3_periph_nvic_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_nvic/moredump/m3_periph_nvic_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2bt/moredump/mb_ap2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2bt/moredump/mb_ap2bt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2pmu/moredump/mb_ap2pmu_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2pmu/moredump/mb_ap2pmu_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2wl/moredump/mb_ap2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2wl/moredump/mb_ap2wl_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_cp2bt/moredump/mb_cp2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_cp2bt/moredump/mb_cp2bt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_cp2wl/moredump/mb_cp2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_cp2wl/moredump/mb_cp2wl_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/perb/moredump/perb_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/perb/moredump/perb_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/pert/moredump/pert_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/pert/moredump/pert_registers.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/hip_signals.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/hip_signals.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/hydra_config.sdb:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/hydra_config.sdb \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/id.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/id.txt \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/log-strings.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/log-strings.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/mib_out.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/mib_out.xml \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/symbols.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/symbols.dbg \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/unicli.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/unicli.dbg \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/unitab.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/unitab.dbg \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/univif.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/univif.dbg \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/debug/wlan/xide_mib.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/xide_mib.dbg \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140_common.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_common.hcf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140_wlan_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_sw.hcf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140_wlan_t_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_t_sw.hcf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/slsi_reg_database.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/slsi_reg_database.bin

PRODUCT_PACKAGES += \
    android.hardware.graphics.composer@2.1-resources_samsung \
    android.hardware.graphics.composer@2.2-resources_samsung \
    android.hardware.graphics.extension.composer3-V1-ndk \
    android.weaver@1.0 \
    libEGL_samsung \
    libGLESv1_CM_samsung \
    libGLESv2_samsung \
    gnss_aidl_lib \
    android.hardware.graphics.mapper@4.0-impl-sgr \
    audio.primary.s5e8845 \
    audio.sec_primary.default \
    gatekeeper.s5e8845 \
    libsecaudiohal_aidl \
    sound_trigger.primary.s5e8845 \
    vulkan.samsung \
    libExtIRTA \
    libExynosC2ComponentStore \
    libExynosC2H264Dec \
    libExynosC2H264Enc \
    libExynosC2HevcDec \
    libExynosC2HevcEnc \
    libExynosC2Vp8Dec \
    libExynosC2Vp8Enc \
    libExynosC2Vp9Dec \
    libExynosC2Vp9Enc \
    libExynosHWCService \
    libIRTA \
    libOpenCL \
    libSGPUOpenCL \
    libSamsungPostProcessConvertor \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    lib_SamsungRec_07010 \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_SRC384_ver320 \
    lib_SoundAlive_play_plus_ver600 \
    lib_SoundBooster_ver2000 \
    lib_profiler \
    lib_soundaliveresampler \
    libacryl \
    libalsautils_sec \
    libarcsoft_dualcam_portraitlighting_preview \
    libaudio-ril \
    libaudioparamupdate \
    libaudioproxy2 \
    libaudioroute_samsung \
    libcsc \
    libdisplaycolor_default \
    libdrm_sgpu \
    libdrmresource \
    libdualcam_refocus_video \
    libegis_fp_normal_sensor_test \
    libeis_core \
    libeis_utils \
    libems_service \
    libengmode_client \
    libenn_common_utils \
    libenn_cpu_operators \
    libenn_engine_lib \
    libenn_model \
    libenn_public_api_cpp_lib \
    libenn_user_driver_cpu \
    libenn_user_driver_gpu_lib \
    libenn_user_driver_unified \
    libenn_user_lib \
    libepic_helper \
    libepicoperator \
    libexynos_sensor_interface \
    libexynosdisplay \
    libexynosgdc \
    libexynosgraphicbuffer \
    libexynosgraphicbuffer_core \
    libexynosscaler \
    libexynosutils \
    libexynosv4l2 \
    libfloatingfeature \
    libgf_in_system_lib \
    libgiantmscl \
    libgmc \
    libhdrwrapper \
    libhermes \
    libhermes_bdbridge \
    libhermes_cred \
    libhwjpeg \
    libhwjsqz \
    libhwvault \
    libion_exynos \
    libisosechw \
    liblastaboxmsg \
    libmpbase \
    libprofileparamstorage \
    libqfp_sensortest \
    libril_sem \
    libsamsungcamerahal \
    libsamsungcamerahalutils \
    libsamsungcamerahwl_impl \
    libsbwchelper \
    libsec-ril \
    libsec2lsi_conversion \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecnativefeature \
    libsecril-client \
    libsehbluetooth_audio_session_aidl \
    libsemnativecarrierfeature \
    libsemseg \
    libsensorlistener \
    libsfp_sensor \
    libsfp_teegw \
    libshctrl \
    libskeymint10device \
    libskeymint_cli \
    libspatializerparamstorage \
    libspeakercalibration \
    libsynaFpSensorTestNwd \
    libteecl \
    libtinyalsa_samsung \
    libuniapi \
    libuniplugin \
    libuuid_vendor \
    libvkmanager_vendor \
    libvpl \
    libwrappergps \
    nfc_nci_sec \
    sensors.sensorhub \
    libaudioeffectoffload \
    libmyspace \
    vendor.samsung.hardware.audio-V1-ndk \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V2-ndk \
    vendor.samsung.hardware.bluetooth.audio-impl \
    vendor.samsung.hardware.camera.device-V1-ndk \
    vendor.samsung.hardware.camera.provider-V1-ndk \
    vendor.samsung.hardware.gnss-V3-ndk \
    vendor.samsung.hardware.keymint-V3-ndk \
    vendor.samsung.hardware.nfc_aidl-V1-ndk \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.security.drk-V1-ndk \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.hermes-V1-ndk \
    vendor.samsung.hardware.thermal-V1-ndk \
    vendor.samsung.hardware.thermal@1.0 \
    vendor.samsung.hardware.vibrator-V5-ndk \
    vendor.samsung.libcolor.custom \
    vendor.samsung_slsi.hardware.epic-V1-ndk \
    vendor.samsung_slsi.hardware.epic@1.0 \
    com.google.android.widevine.nonupdatable \
    HotwordEnrollmentOKGoogleEx4CORTEXM4 \
    HotwordEnrollmentXGoogleEx4CORTEXM4 \
    com.android.hotwordenrollment.common.util \
    hwc3.xml \
    iweaver_aidl_v2_manifest.xml \
    sec-nfc-service.xml \
    secaudiohalaidl_manifest.xml \
    vendor.samsung.hardware.camera.provider-service.xml \
    vendor.samsung.hardware.radio.exclude.slsi.xml \
    vendor.samsung.hardware.radio_manifest_2_34.xml \
    vendor.samsung.hardware.security.hermes.xml \
    vendor.samsung.hardware.sehradio_manifest_2_34.xml \
    vendor.samsung.hardware.vibrator-default.xml \
    dmd \
    epic \
    hermesd \
    android.hardware.gatekeeper-service \
    android.hardware.graphics.allocator-aidl-service-sgr \
    android.hardware.graphics.composer3-service.exynos \
    android.hardware.security.keymint-service.samsung \
    gps \
    gpsd_K44 \
    rild \
    samsung.hardware.media.c2@1.2-service \
    sec.android.hardware.nfc-service \
    secaudiohalaidl \
    vendor.samsung.hardware.camera.provider-service_64 \
    vendor.samsung.hardware.gnss-service \
    vendor.samsung.hardware.security.hermes-service \
    vendor.samsung.hardware.vibrator-service \
    init.insmod \
    tzdaemon \
    tzts_daemon

PRODUCT_PACKAGES += \
    vendor_Khronos_OpenCL_vendors_samsung_icd
